[project]
name = "call-me-maybe"
version = "0.1.0"
description = "translate natural language prompts into structured function call"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy>=2.4.6",
    "pydantic>=2.13.5",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }
